### PR TITLE
Added Simplified Chinese

### PR DESCRIPTION
**Pull request by L1cardo**

### CODE REVIEW

**Comment by L1cardo** [comment]
Please merge this pull request and make a new build.
I failed building a new version.
I am in China and Carthage didn't work well because of the Internet issue .

**Comment by JK3Y** [comment]
Thank you for this! I will review this when I have the opportunity in the next couple of days and post a build as well.

**Comment by L1cardo** [comment]
I am here to bother you again .
Can you add a "cancel download" button ? There is only stop button now .

**Comment by JK3Y** [comment]
Hello, just an update to say that I am working on a fresh build of this right now. There were some hiccups with the Carthage build and I'm ironing out those right now. As for cancelling downloads, the stop button acts as both a way to pause downloads and the cancel button; if the clear button is clicked then any stopped downloads will be removed from the download list effectively cancelling them. Because of this functionality a cancel download button will not be added into the UI. Feel free to respond with a translation for "Remove completed and stopped downloads" and I will place that in the tooltip for the clear button so that this is clear to users. Thanks!

**Comment by L1cardo** [comment]
移除已完成与已暂停项目    for   Remove completed and stopped downloads

**Comment by JK3Y** [comment]
Excellent, thank you. I have published a new release and credited you in the README for the translation work.

**Comment by L1cardo** [comment]
Hahaha    thanks!

**Pull request merged**
